#!/usr/bin/env bash
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
	source /etc/bash_completion
fi

if [ -f /etc/profile.d/bash_completion.sh ]; then
	source /etc/profile.d/bash_completion.sh
fi

if [ -f /usr/lib/node_modules/npm/lib/utils/completion.sh ]; then
	source /usr/lib/node_modules/npm/lib/utils/completion.sh
fi

# Disable CTRL-S & CTRL-Q
stty stop ''
stty start ''
stty -ixon
stty -ixoff

###################################################################################################
# History Settings
###################################################################################################
# bash_history: Ignore dups and add timestamp
HISTCONTROL=ignoreboth
HISTTIMEFORMAT="%d/%m/%y %T "
# append to the history file, don't overwrite it
shopt -s histappend
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Lock and Load a custom theme file
[[ ${TERM} != "linux" ]] && source "${RC_PATH}/ps1/shell_prompt.sh"

# Write history after every command
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

source <(cat "${XDG_CONFIG_HOME}/completion/bash/"*)

trap _unsudo exit
