#!/bin/bash

function extract {
	if [ -z "$1" ]; then
		# display usage if no parameters given
		echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
	else
		if [ -f $1 ] ; then
			NAME=${1%.*}
			mkdir $NAME && cd $NAME
			case $1 in
				*.tar.bz2)   tar xvjf ../$1    ;;
				*.tar.gz)    tar xvzf ../$1    ;;
				*.tar.xz)    tar xvJf ../$1    ;;
				*.lzma)      unlzma ../$1      ;;
				*.bz2)       bunzip2 ../$1     ;;
				*.rar)       unrar x -ad ../$1 ;;
				*.gz)        gunzip ../$1      ;;
				*.tar)       tar xvf ../$1     ;;
				*.tbz2)      tar xvjf ../$1    ;;
				*.tgz)       tar xvzf ../$1    ;;
				*.zip)       unzip ../$1       ;;
				*.Z)         uncompress ../$1  ;;
				*.7z)        7z x ../$1        ;;
				*.xz)        unxz ../$1        ;;
				*.exe)       cabextract ../$1  ;;
				*)           echo "extract: '$1' - unknown archive method" ;;
			esac
		else
			echo "$1 - file does not exist"
		fi
	fi
}

## archives
function ac() { # compress a file or folder
	case "$1" in
		tar.bz2|.tar.bz2) tar cvjf "${2%%/}.tar.bz2" "${2%%/}/" ;;
		tbz2|.tbz2) tar cvjf "${2%%/}.tbz2" "${2%%/}/" ;;
		tbz|.tbz) tar cvjf "${2%%/}.tbz" "${2%%/}/" ;;
		tar.gz|.tar.gz) tar cvzf "${2%%/}.tar.gz" "${2%%/}/" ;;
		tar.Z|.tar.Z) tar Zcvf "${2%%/}.tar.Z" "${2%%/}/" ;;
		tgz|.tgz) tar cvjf "${2%%/}.tgz" "${2%%/}/" ;;
		tar|.tar) tar cvf "${2%%/}.tar" "${2%%/}/" ;;
		rar|.rar) rar a "${2%%/}.rar" "${2%%/}/" ;;
		zip|.zip) zip -r9 "${2}.zip" "$2" ;;
		7z|.7z) 7z a "${2}.7z" "$2" ;;
		lzo|.lzo) lzop -v "$2" ;;
		gz|.gz) gzip -v "$2" ;;
		bz2|.bz2) bzip2 -v "$2" ;;
		xz|.xz) xz -v "$2" ;;
		lzma|.lzma) lzma -v "$2" ;;
		*) echo "Error, please go away.";;
	esac
}

function ad() { # decompress
	for i in ${@}; do
		if [ -f ${i} ] ; then
			case ${i} in
				*.tar)       tar xvf "${i}"     ;;
				*.tbz2)      tar xvjf "${i}"    ;;
				*.tgz)       tar xvzf "${i}"    ;;
				*.tar.bz2)   tar xvjf "${i}"    ;;
				*.tar.gz)    tar xvzf "${i}"    ;;
				*.tar.xz)    tar xvJf "${i}"    ;;
				*.lzma)      unlzma "${i}"      ;;
				*.bz2)       bunzip2 "${i}"     ;;
				*.rar)       unrar x -ad "${i}" || 7z x "${i}";;
				*.gz)        gunzip "${i}"      ;;
				*.zip)       unzip "${i}"       ;;
				*.Z)         uncompress "${i}"  ;;
				*.7z)        7z x "${i}"        ;;
				*.xz)        unxz "${i}"        ;;
				*.exe)       cabextract "${i}"  ;;
				*)           echo "extract: '${i}' - unknown archive method" ;;
			esac
		else
			echo "${i} - file does not exist"
		fi
	done
}

function al() { # list content of archive but don't unpack
	case "$1" in
		*.tar.bz2|*.tbz2|*.tbz) tar -jtf "$1" ;;
		*.tar.gz|*.tar.Z) tar -ztf "$1" ;;
		*.tar|*.tgz) tar -tf "$1" ;;
		*.gz) gzip -l "$1" ;;
		*.rar) rar vb "$1" ;;
		*.zip) unzip -l "$1" ;;
		*.7z) 7z l "$1" ;;
		*.lzo) lzop -l "$1" ;;
		*.xz|*.txz|*.lzma|*.tlz) xz -l "$1" ;;
		*) echo "Error, please go away.";;
	esac
}

function _unsudo() {
	if [[ ${EUID} -eq 0 && -n ${SUDO_USER} && ${HOME} = $(eval echo ~${SUDO_USER}) ]]; then
		local SUDO_GROUP=$(id -g -n ${SUDO_USER})
		chown -R ${SUDO_USER}:${SUDO_GROUP} ${HOME}
		exit
	fi
}

function grep_invalid_utf8 () {
	perl -l -ne '/^([\000-\177]|[\300-\337][\200-\277]|[\340-\357][\200-\277]{2}|[\360-\367][\200-\277]{3}|[\370-\373][\200-\277]{4}|[\374-\375][\200-\277]{5})*$/ or print'
}

function fix_invalid_utf8 () {
	find | grep-invalid-utf8 | rename 'BEGIN {binmode STDIN, ":encoding(latin1)"; use Encode;}$_=encode("utf8", $_)'
}

function git_remove_submodule() {
	SUBMODULE_NAME=$(echo "${1}" | sed 's/\/$//'); shift

	if git submodule status "${SUBMODULE_NAME}" >/dev/null 2>&1; then
		git submodule deinit -f "${SUBMODULE_NAME}"
		git rm --cached "${SUBMODULE_NAME}"
		rm -rf .git/modules/${SUBMODULE_NAME}
		rm -rf ${SUBMODULE_NAME}
		git config -f .gitmodules --remove-section "submodule.${SUBMODULE_NAME}"
	else
		[ $# -gt 0 ] && echo "fatal: Submodule '${SUBMODULE_NAME}' not found" 1>&2
		exit 1
	fi
}

[[ -s ${HOME}/.fzf ]] && source ${HOME}/.config/bash/fzf_functions
