k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: true
  enableImageScan: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: true
  currentContext: kubernetes-admin@ct-cola-k8s-main2
  currentCluster: ct-cola-k8s-main2
  keepMissingClusters: false
  clusters:
    ct-cola-k8s-main2:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - monitoring
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    fhe3-vi-k8s-main3:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - all
        - monitoring
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens
  disablePodCounting: false
