#!/usr/bin/env bash
#
# vim: ts=2 sw=2 et ff=unix ft=bash syntax=sh

# Read functions
source "${NREDF_DOT_PATH}/shell/common/nredf_functions"

_nredf_get_sys_info
_nredf_set_defaults
_nredf_set_ssh_agent
[[ -z ${SUDO_COMMAND} ]] && _nredf_sync_dotfiles

_nredf_set_local
[[ -z ${SUDO_COMMAND} ]] && _nredf_cleanup_dotfiles

[[ -z ${SUDO_COMMAND} ]] && _nredf_install_tools

# run shell exclusive things
echo -e "\033[1mCustomizing Shell\033[0m"
source "${NREDF_RC_PATH}/rc"

if [[ -d "${ASDF_DIR}" ]]; then
  source "${ASDF_DIR}/asdf.sh"
  source "${ASDF_DIR}/completions/asdf.bash"
  fpath=("${ASDF_DIR}/completions ${fpath[@]}")
fi
_nredf_os_specific
_nredf_remote_multiplexer
